server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: spacex-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/spacex_dashboard}
    username: ${POSTGRES_USER:spacex}
    password: ${POSTGRES_PASSWORD:secret123}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 5000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 2000

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

jwt:
  secret: ${JWT_SECRET:0123456789abcdef0123456789abcdef0123456789abcdef}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  header: Authorization
  token-prefix: Bearer

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type

logging:
  level:
    root: INFO
    com.spacex: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.transaction: DEBUG
    com.spacex.launcher: DEBUG
  pattern:
    console: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/spacex-backend.log

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
